### ISSUE TITLE
Should read sourcemaps from `compiler.inputFileSystem`

### ISSUE THREAD

**Issue by aletorrado** [webpack-contrib/source-map-loader#103]
Hi! This loader is using the default node `fs` module to read the sourcemaps, which breaks compatibility when compiling using virtual filesystems.

It should use the fs API setted on the webpack compiler instance.

**Comment by evilebottnawi** [comment]
Yes, it is a bug, duplicate of #2 and will be fixed in the next major release, ETA is the next week
