### ISSUE TITLE
"File URL path must be absolute" on Windows

### ISSUE THREAD

**Issue by Domiii** [webpack-contrib/source-map-loader#116]
- Operating System: Windows
- Node Version: 13.*
- NPM Version: yarn 1.21.1 (does not matter)
- webpack Version: 4.*
- source-map-loader Version: 1.0.0

### Problem description (actual behavior)

On Windows, cryptic warnings are emitted, saying:

> WARNING in d:/my/library/dist/index.js
> Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
> File URL path must be absolute
>  @ ./myProgram.js 8:19-42

### Expected Behavior

No warning. Does not happen on Mac.

### How to reproduce?

No way to easily produce a minimal example of this problem, since the given warning is too cryptic.

#### Step 1

I found out that the error message indicates one of two possible problems:
1. Incorrect/unrecognized file/path for path/file conversion (as seen [here](https://stackoverflow.com/questions/60800239/is-there-a-bug-in-node-js-pathtofileurl-fileurltopath))
2. An incorrect file URL on Windows, as explained in node documentation ([here](https://nodejs.org/api/fs.html#fs_url_object_support)): 
> On Windows, file: URLs with a host name convert to UNC paths, while file: URLs with drive letters convert to local absolute paths. file: URLs without a host name nor a drive letter will result in a throw

#### Step 2: Debugging source-map-loader

I went into `dist/index.js` and supplemented the two calls to `this.emitWarning(error)` with `console.error(error)`. After snooping around a bit more, I found that this makes the problem entirely visible:

I added `console.error('fetchFromUrl failed at', `>>${source}<<`, ':\n', error);` to [the `catch` block around line 93 of the original source](https://github.com/webpack-contrib/source-map-loader/blob/4d043f0e0ce270f8979f3f1efd5b7ce426793d64/src/index.js#L93) (NOTE: the `source` variable apparently is the url to the sourcemapped file); yielding error messages like this:

> fetchFromUrl failed at >>file:///webpack/universalModuleDefinition<< :
> TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
>     at getPathFromURLWin32 (internal/url.js:1310:13)
>     at Object.fileURLToPath (internal/url.js:1342:22)
>     at fetchFromURL (d:\my\project\node_modules\source-map-loader\dist\utils.js:151:40)
>     at d:\my\project\node_modules\source-map-loader\dist\index.js:89:41
>     at Array.map (<anonymous>)
>     at Object.loader (d:\my\project\node_modules\source-map-loader\dist\index.js:77:57)

## Analysis Results

It does not seem to handle all kinds of "special" webpack urls. More invalid url examples include:

> file:///webpack/universalModuleDefinition
> file:///webpack/bootstrap
> file:///external "colors/safe"
> file:///external "core-js/modules/es.array.concat"
> file:///external "lodash/isObject"
> file:///external "core-js/modules/web.timers"

and many more...

Also, possibly related to the fact that the imported library is `umd`?

## Solutions?

Not sure what to do here. But getting rid of those annoying warnings would be a great start (as I am generally not too concerned about source maps to these sorts of files to begin with).

**Comment by cap-Bernardito** [comment]
You can remove warnings like this:

`webpack.config.js`

```js
module.exports = {
  stats: {
    warningsFilter: [/File URL path must be absolute/],
  },
};
```

https://webpack.js.org/loaders/source-map-loader/#ignoring-warnings

**Comment by Allegra9** [comment]
I started getting these warnings after the update to v1.0.0

`Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "webpack:///fileName.js" URL is not supported`

Operating System: Mac
Node Version: 12
webpack Version: 4.*
source-map-loader Version: 1.0.0

**Comment by evilebottnawi** [comment]
@Domiii @Allegra9 we can't resolve `webpack://` because we don't know real path to source maps generated from other webpack build, `webpack://` is `context` of your configuration and we don't know the value, anyway can you provide a source file with `webpack://`, We can try to resolve it like `webpack://` === `directly where places file`, it handle 99% cases

**Comment by NeKJ** [comment]
I'm having the same issue and I get hundreds of these warnings:
```
Failed to parse source map: "webpack://app/webpack/index URL is not supported
```
Using version 1.0.0

@evilebottnawi I fail to understand what you have written. What do you mean 'we can try to resolve it like....'? Can you explain in detail how I can get this fixed?

**Comment by evilebottnawi** [comment]
@NeKJ We don't know how parse `webpack://` protocol in source maps, each `source` is `URL`, from `URL` we get file path and read it to include in source map. You can find `webpack://` protocol in the `sources` field of some libraries. I think we can fix it.

Can you provide simple reproducible test repo?

**Comment by icatalina** [comment]
👋 @evilebottnawi! Same issue here. I created a reproducible test-repo. https://github.com/icatalina/source-map-loader-116

Just clone it and:
```
cd repo1
npm ci
npm start
cd ../repo2
npm ci
npm start
```

and you can see the errors:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/4542735/85642074-b6d52c80-b6d3-11ea-8a40-d91407a544ef.png">

**Comment by evilebottnawi** [comment]
Thanks!
