### ISSUE TITLE
Failed to parse source map from [path] warning

### ISSUE THREAD

**Issue by shimizacken** [webpack-contrib/source-map-loader#119]
- Operating System: macOS Catalina `10.15.6`
- Node Version: `12.18.2`
- NPM Version: `6.14.5`
- Yarn version: `1.22.4`
- webpack Version: `4.43.0`
- source-map-loader version: `1.0.1`

### Actual Behavior

`Failed to parse source map from [path] file: Error: ENOENT: no such file or directory, open [path]` warnings are logged in the terminal (as well in the browser console log).

#### Remarks
- It failed to load all [`standardized-audio-context`](https://www.npmjs.com/package/standardized-audio-context) package source map files
- Seems that `source-map-loader` treats the path `//# sourceMappingURL=/build/es2019/constants.js.map` as an absolute path, what cause the failure `Error: ENOENT: no such file or directory`
- For my test, removing the prefixed slash `/` from the path `/build/es2019/constants.js.map` fixes the issue, so:
```js
// not work 😢
//# sourceMappingURL=/build/es2019/constants.js.map

// work 😍
//# sourceMappingURL=build/es2019/constants.js.map
```

### Expected Behavior

No `Failed to parse source map from...` warnings should logged in the terminal and in the browser console log.

### Code

```js
{
  test: /\.js$/,
  enforce: 'pre',
  use: ['source-map-loader'],
},
```

Example of how the `sourceMappingURL` directive that fails looks like:
```js
//# sourceMappingURL=/build/es2019/constants.js.map
```

### Prerequisite
Web app project that make use of `source-map-loader`

### Steps
1. Install [`standardized-audio-context`](https://www.npmjs.com/package/standardized-audio-context) package
2. Import any module from `standardized-audio-context` into a `*.js/*.ts` file
3. Start/build the project

**Comment by evilebottnawi** [comment]
Interesting case, if you open it locally it was resolved as absolute path, if you open it in browsers it is server-relative URLs, so usually nobody uses this, but we can handle this case, so let's mark it as feature, not bug

**Comment by shimizacken** [comment]
@evilebottnawi Thank you for the fast response and a fix!

However, after installing the latest version `1.0.2`, seems that the issue is still reproducing with the same warnings logged in the terminal as before, for the same library `standardized-audio-context` .

I noticed that the paths contain duplication of the relative path:

Map files in the root folder duplicates: `/build/es2019/`:
```bash
file: Error: ENOENT: no such file or directory, open /Users/shimiz/Documents/[project folder]/node_modules/standardized-audio-context/build/es2019/build/es2019/constants.js.map
```

Deeper map files duplicates: `/build/es2019/types/`:
```bash
file: Error: ENOENT: no such file or directory, open '/Users/shimiz/Documents/[project folder]/node_modules/standardized-audio-context/build/es2019/types/build/es2019/types/abort-error-factory.js.map
```

**Comment by evilebottnawi** [comment]
@shimizacken I investigate this issue and I'm afraid to say that we cannot fix it, `sourceMappingURL` is strange:
```
//# sourceMappingURL=/build/es2019/factories/native-constant-source-node-factory.js.map
```

In file `node_modules/standardized-audio-context/build/es2019/factories/native-constant-source-node-factory.js`

it is relative to package root, but we don't know it is package or not, this would require additional logic that would improve performance dramatically. 

Right `sourceMappingURL`:
```
//# sourceMappingURL=./native-constant-source-node-factory.js.map
```

```
//# sourceMappingURL=native-constant-source-node-factory.js.map
```

Ideally it should be always relative to file, not to directory/package root or other contexts

**Comment by evilebottnawi** [comment]
But maybe we can implement the `fallback` option using this syntax:
```js
fallback: {
  regexp: '/right/path/to/file'
}
```

**Comment by shimizacken** [comment]
@evilebottnawi thank you. Perhaps I'll open an issue for `standardized-audio-context` instead 👍

**Comment by evilebottnawi** [comment]
@shimizacken yes, let's open an issue and wait an answer, if they will not fix it, I will think about it deeply, and provide fallback for this cases

**Comment by shimizacken** [comment]
> @shimizacken yes, let's open an issue and wait an answer, if they will not fix it, I will think about it deeply, and provide fallback for this cases

@evilebottnawi Cool! Opened an issue https://github.com/chrisguttandin/standardized-audio-context/issues/954, please let me know if it's well described

**Comment by shimizacken** [comment]
@evilebottnawi  Thanks for the help. I can confirm that the issue fixed https://github.com/chrisguttandin/standardized-audio-context/issues/954 and closed 🙂
