### ISSUE TITLE
Failed to parse source map ENOENT when sources is not a valid file path

### ISSUE THREAD

**Issue by hedgepigdaniel** [webpack-contrib/source-map-loader#134]
- webpack Version: 4
- source-map-loader Version: 1.1.2

### Expected Behavior

Source maps should be parsed correctly and mappings should be included for all files that have `sourcesContent` or for which `sources` points to a valid file (even if there are some sources for which the values are invalid/missing).

### Actual Behavior

source maps generated with the Google Closure compiler are not parsed at all.

This is because they contain some sources which are not present on the filesystem, and/or "sources" like `" [synthetic:es6/util/arrayiterator] "`. See https://github.com/google/closure-compiler-js/issues/25

```
Failed to parse source map from 'node_modules/shaka-player/node_modules/google-closure-library/closure/goog/base.js' file: Error: ENOENT: no such file or directory, open 'node_modules/shaka-player/node_modules/google-closure-library/closure/goog/base.js'
```

```
Failed to parse source map from 'node_modules/shaka-player/dist/ [synthetic:util/global] ' file: Error: ENOENT: no such file or directory, open 'node_modules/shaka-player/dist/ [synthetic:util/global] '
```

Obviously the mappings referring to these source files will not work because they are not present, but the other mappings for files that are present should still work.

### How Do We Reproduce?

Applying `source-map-loader` to the latest build of https://github.com/google/shaka-player triggers the error.

**Comment by alexander-akait** [comment]
> even if there are some sources for which the values are invalid/missing

No, source maps will be broken in this case, even we provide options to filter you still have invalid mapping, library source maps should not contain this stuff

**Comment by hedgepigdaniel** [comment]
Sorry I made a mistake - I though that the entire source map wasn't working, but in fact its only the invalid sources that don't work. No problem :)
