### ISSUE TITLE
Specify webpack version on readme

### ISSUE THREAD

**Issue by danielo515** [webpack-contrib/source-map-loader#142]
Documentation Is:

- [ ] Missing
- [x] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

I think some kind of mapping for which versions of webpack goes with with which versions of this library.
Configuring webpack is a one-time thing, and then you forget about it. Chasing down which webpack version each loader needs it's a tedious task. Having this info directly on the readme will really help

### Your Proposal for Changes
I think that a simple table will be enough.

**Comment by alexander-akait** [comment]
npm and yarn output warning about this, why you ignore?

**Comment by danielo515** [comment]
I am not ignoring anything. All npm or yarn tells you is that your current version is missing X.X.X peer webpack version. That does not tells you which version of this library to instal for YOUR webpack version. I think that having to navigate the different versions of this package.json just to find what version to use is very inefficient.

**Comment by alexander-akait** [comment]
I want to close this issue, because webpack v4 is fully deprecated and please migrate on wepack v5
