### ISSUE TITLE
this.getOptions is not a function

### ISSUE THREAD

**Issue by patrikniebur** [webpack-contrib/source-map-loader#144]
- Operating System: OSX11.1
- Node Version: v12.20.1
- NPM Version:6.14.10
- webpack Version: 4.44.2
- source-map-loader Version:2.0.1

### Expected Behavior
Build succeeding

### Actual Behavior
Build fails with the following error:  
```
TypeError: this.getOptions is not a function
    at Object.loader
```

### Code

I will include minimum reproducible example later

Currently I work around the issue by patching this part:
https://github.com/webpack-contrib/source-map-loader/blob/master/src/index.js#L10-L11

with 
```js
  let options = {};
  try {
    options = this.getOptions(_options.default);
  } catch (e) { }
```
and that makes things work as expected.

### How Do We Reproduce?
Apologies for not including more details, I'll try to get to this later and debug more myself. In the meantime I was hoping you could advise what could be causing `this.getOptions` not to be a function. 
Thanks!

**Comment by das-peter** [comment]
Just came across this issue too.
Try catch block seems to do the trick for me too.
Will test further.

**Comment by das-peter** [comment]
Oh I see - as of 2.0.0 webpack 5 is minimum requirement as of https://webpack.js.org/migrate/5/#getoptions-method-for-loaders

**Comment by alexander-akait** [comment]
Yes, you need webpack v5 to use the latest version `source-map-loader`, nothing to fix here, please read changelog when you update something

**Comment by patrikniebur** [comment]
Right, I missed this. Thanks for help

**Comment by g-almabek** [comment]
Hi, @alexander-akait 
I'm using latest version of webpack v5.74.0, but still I am getting this error.
Could you please advise?

**Comment by alexander-akait** [comment]
@g-almabek It means you sitll use webpack v4
