### ISSUE TITLE
this.getOptions is not a function when try to launch NextJS app

### ISSUE THREAD

**Issue by Tonetete** [webpack-contrib/source-map-loader#145]
- Operating System: OSX 11.3 beta
- Node Version: 12.19.0
- NPM Version: 6.14.8
- webpack Version: 4.41.2
- source-map-loader Version: 2.0.1

### Expected Behavior

When I run my NextJS app, should bundle and link the sources map and finally run the app successfully.

### Actual Behavior

NextJS app is not launched successfully with runtime errors when try to run source-map-loader:

```sh
error - ../node_modules/next/node_modules/@next/react-refresh-utils/runtime.js
TypeError: this.getOptions is not a function
```

### Code

This is the current implementation for next.config.js

```js
module.exports = {
  webpack: (config, options) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config
    // Load source maps in dev mode
    if (config.mode === "development") {
      config.module.rules.push({
        test: /\.js$/,
        use: ["source-map-loader"],
        enforce: "pre",
      });
    }

    config.plugins.push(new options.webpack.IgnorePlugin(/\/__tests__\//));

    // Important: return the modified config
    return config;
  },
};
```

### How Do We Reproduce?

Yo need to create a boilerplate app with NextJS and install source-map-loader and create a `next.config.js` by simply running the follow commands:

`npx create-next-app nextjs-example --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"`

and install the dependency:

`npm i -D source-map-loader`

and create a **next.config.js** at the root the project and copy the code above and run:

`npm run dev`

and you'll be able to reproduce this error. It looks like source-map-loader is not able to access webpack context or whatever the getOptions method is located.

**Comment by ffarthbe** [comment]
@Tonetete Tonetete,I have the same problem,have you solved it?

**Comment by ffarthbe** [comment]
https://github.com/webpack/loader-utils/issues/56#issue-206266981

**Comment by ffarthbe** [comment]
@Tonetete herehttps://github.com/webpack/loader-utils/issues/56#issue-206266981

**Comment by alexander-akait** [comment]
You need webpack v5 to use latest version of `sourcer-map-loader`

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/source-map-loader/releases/tag/v2.0.0

**Comment by ffarthbe** [comment]
@Tonetete https://github.com/webpack/loader-utils/issues/56#issue-206266981 here
![Uploading image.png…]()

**Comment by Tonetete** [comment]
Thank so much! I just upgraded to webpack 5 and its working flawlessly! Some points that are worth to mention in order to make it works:

- You need to add resolutions for webpack pointing to 5, otherwise it'll stick to 4 version since that's the current version NextJS is using under the hood. You can learn more here: https://nextjs.org/blog/next-9-5#webpack-5-support-beta
- It should work out-of-the-box but it wasn't my case and I'm guessing because custom webpack configuration in next.config.js you'll also need to add this property:

```js
future: {
    webpack5: true,
  }
```

This way we're telling NextJS to run custom config under webpack 5. Probably if you hit this thread in a future, it shouldn't be necessary these tweaks I did but just to bear in mind if installing webpack 5 it wasn't enough.

Regards!

**Comment by arielnmz-iws** [comment]
How can I make CRACO use webpack 5?
