### ISSUE TITLE
Null in sources content skips reading of file

### ISSUE THREAD

**Issue by ilgonmic** [webpack-contrib/source-map-loader#147]
- Operating System: macOS BigSur 11.2.3
- Node Version: 16.0.0
- NPM Version: 7.10.0
- webpack Version: 5.37.0
- source-map-loader Version: 2.0.1

### Expected Behavior

`null` in sources content considered as sources should be retrieved by name (http://sourcemaps.info/spec.html)

### Actual Behavior

`null` in sources content considered as skip reading of file

### Code

```js
{"version":3,"file":"untitled.js","sources":["kotlin-wrappers-kotlin-react-dom-jsLegacy.js","../../../../../src/main/kotlin/client.kt","../../../../../src/main/kotlin/welcome.kt"],"sourcesContent":[null,null,null], "names":[], "mappings":";"}
```

### How Do We Reproduce?

Use source map with `null` in `sourcesContent` but having source file in file system.

**Comment by alexander-akait** [comment]
I see, thanks, I will fix it

**Comment by ilgonmic** [comment]
I have fix in branch, I am testing it. So feel free to use it
https://github.com/ilgonmic/source-map-loader/tree/fix-null-source-content

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/source-map-loader/pull/148
