### ISSUE TITLE
Regex for matching URLs is not strict enough

### ISSUE THREAD

**Issue by raybooysen** [webpack-contrib/source-map-loader#16]
Hit this today, we're using a package which used the source-map-support package.  In their code they have a comment that, to the loader, looks like a source map url.  I've opened an issue here:  
https://github.com/evanw/node-source-map-support/issues/136

Is it possible to make the regex more strict?

**Comment by michael-ciniawsky** [comment]
@raybooysen Maybe fixed by #31, I reopen if it shouldn't be the case 😛
