### ISSUE TITLE
  ignoreWarnings: [/Failed to parse source map/], not work , webpack still output the warning message

### ISSUE THREAD

**Issue by lovetingyuan** [webpack-contrib/source-map-loader#178]
warning  in ./node_modules/mbiz-columns-template/dist/index.js

Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '....' file: Error: ENOENT: no such file or directory, open '...'

 {
  module: { rules: [ [Object], [Object], [Object], [Object], [Object] ] },
  ignoreWarnings: [ /Failed to parse source map/]
}

**Comment by alexander-akait** [comment]
It means you have a library/something with the source maps comment, byt without source maps files, please fill out the issue template and I will help, otherwise I can't say there is a problem, thank you
