### ISSUE TITLE
Style loader causes wrong regex match

### ISSUE THREAD

**Issue by aleckravets** [webpack-contrib/source-map-loader#19]
If the loaded resource is bundled with webpack+style-loader and minified (no spaces), source map loader triggers the false regex match due the the following line in the style loader's runtime code (addStyles.js:235):

  `css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";`

and fails trying to parse this string.

**Comment by michael-ciniawsky** [comment]
Should be fixed by #31
