### ISSUE TITLE
Can not work with tti-polyfill

### ISSUE THREAD

**Issue by childrentime** [webpack-contrib/source-map-loader#215]
### Bug report

Import tti-polyfill to your entry file and It will broke.

```js
npm i tti-polyfil
import ttiPolyfill from "tti-polyfill";
```

### Actual Behavior

Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/lianwenwu/work/demo/webpack-react/node_modules/tti-polyfill/ [synthetic:util/global] ' file: Error: ENOENT: no such file or directory, open '/work/demo/webpack-react/node_modules/tti-polyfill/ [synthetic:util/global] '

### Expected Behavior

works well.

### How Do We Reproduce?

import it to any js file. And use source-map-loader to the js files.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
  webpack-cli@5.1.1

**Comment by alexander-akait** [comment]
As you can see from the error message, there is not file `/work/demo/webpack-react/node_modules/tti-polyfill/ [synthetic:util/global] `, it means source maps are broken

**Comment by alexander-akait** [comment]
You can use `/node_modules[/\\]tti-polyfill/` regexp

**Comment by childrentime** [comment]
Alright. I was initially curious as to why it was failing, but it seems like it works this way too. I hate old projects🥹.
