### ISSUE TITLE
How to re-map source root?

### ISSUE THREAD

**Issue by unional** [webpack-contrib/source-map-loader#24]
I'm using `webpack` to bundle a single build:

```js
{
  output: {
    library: 'GlobalStore'
    libraryTarget: 'var'
  },
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js?$/,
        loader: "source-map-loader"
      }
    ]
  }
```

The resulting source map path is a relative path:
![image](https://cloud.githubusercontent.com/assets/3254987/21881806/a35aa74c-d85c-11e6-843c-771447e170a7.png)

I get around it by changing the `sourceRoot` in `tsconfig.json`:
```js
// tsconfig.json
{
  "compilerOptions": {
    "sourceRoot": "/global-store"
    ...
  }
}
```

This way, the source map is displayed nicely in the browser:
![image](https://cloud.githubusercontent.com/assets/3254987/21881882/f13c8f3e-d85c-11e6-85f4-e5f0489c62b9.png)

But such config is not liked by coverage tools such as `coveralls`.
It seems like the way I'm doing it is a hack.

I would like to see how to do it correctly.
Is there a way I can tell `source-map-loader` to map `../../src` to `/global-store'?

You can see the code here:
https://github.com/unional/global-store/tree/1b26a0cde30b5785639f68b0a34b19c87495800b

**Comment by michael-ciniawsky** [comment]
@unional Maybe #9 is what your are looking for :). Could take a look please

**Comment by unional** [comment]
Thanks. I have resolved this issue by the following:

```js
const pjson = require('./package.json')

module.exports = {
  devtool: 'source-map',
  module: {
    rules: [
      {
        enforce: 'pre',
        loader: "source-map-loader",
        test: /\.js?$/
      }
    ]
  },
  output: {
    devtoolModuleFilenameTemplate: (info) => {
      if (info.identifier.lastIndexOf('.ts') === info.identifier.length - 3) {
        return `webpack:///${pjson.name}/${info.resource.slice(9)}`
      }
      else {
        return `webpack:///${info.resourcePath}`
      }
    }
  }
}
```
