### ISSUE TITLE
Inline source map with extended data uri syntax causes an error

### ISSUE THREAD

**Issue by asapach** [webpack-contrib/source-map-loader#25]
One of the libraries I'm using has the following inline source map:
```
//# sourceMappingURL=data:application/json;charset=utf-8;base64,...
```
This doesn't match the regexp: [` /data:[^;\n]+;base64,(.*)/`](https://github.com/webpack-contrib/source-map-loader/blob/00c324ceb61f4f849b43b6b9c5b723879ca65559/index.js#L17), because it specifies an encoding in the `mediatype`, but it's perfectly valid according to the spec: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

This results in the wrong code path being taken and the data URI is interpreted as a URL, which results in an error: `Cannot find SourceMap 'data:application/json;charset=utf-8;base64,...`

I suggest relaxing the regexp to allow semicolon:  `/data:[^\n]+;base64,(.*)/`

**Comment by nrdobie** [comment]
👍  Having the same issue with PostCSS.

**Comment by CNDW** [comment]
this is fixed by https://github.com/webpack-contrib/source-map-loader/pull/21/files, it's almost 2 months old now, can we get this fixed pushed through?

**Comment by michael-ciniawsky** [comment]
Closing since #21 was merge
