### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by ecarlisle** [webpack-contrib/source-map-loader#32]
Hi! I really appreciate `source-map-loader`! It's definitely a big help in debugging.

I want to understand, however, that it's doing exactly what I think it is. This will help in optimizing my bundling process.  Here's my understanding so far:

1. As a pre-loader, `source-map-loader` will find the inline and external source maps for all libraries included in a build.
2.  It will process all of these maps into a single map. That map will then be placed into the bundled JavaScript as per the WebPack source map configuration (e.g. cheap-module-eval-source-map, eval-source-map, etc...).

Does this ring true? I'd appreciate any information you can offer and would be happy to place this in a documentation PR in case this is helpful for others.

Thanks!

**Comment by michael-ciniawsky** [comment]
@ecarlisle While I can't answer that question 💯 , the initial intro you wrote sounds pretty good so far 👍 when you have time please feel free to a send PR with your writings and additions can be discussed and added later then 😛

**Comment by ecarlisle** [comment]
@michael-ciniawsky : Thank you! I did some testing yesterday and am more confident about my description above.  I'll submit a PR asap.

Thanks!

**Comment by ecarlisle** [comment]
Hi!
I finally had a chance to write some copy.  Please see the fork here:
https://github.com/ecarlisle/source-map-loader/tree/elaborate-on-primary-documentation
Let me know if you're like to make this into a PR.  All feedback, corrections are welcome.

Thanks!
Eric

**Comment by michael-ciniawsky** [comment]
Open PR 🙃  and corrections can be discussed/corrected there then, looks good, only a few nits in styling 😛 thx very much

**Comment by ecarlisle** [comment]
PR added at https://github.com/webpack-contrib/source-map-loader/pull/35

**Comment by cap-Bernardito** [comment]
PR #37 was merged
