### ISSUE TITLE
Regexp is matching non-last sourceMapURL

### ISSUE THREAD

**Issue by AndrewKirkovski** [webpack-contrib/source-map-loader#38]
Regexp matches `data:application/json;base64,"+btoa(unescape(encod` which is not last sourcemap url
Should match last one

For file https://github.com/spiral-modules/toolkit/blob/cc18539600225996866d70d3952d0a5c95b2ff74/resources/scripts/sf.toolkit.js (Generated by webpack)

**Comment by AndrewKirkovski** [comment]
Update: upon further investigation it seems both `regex1` and `regex2` matches, but first match is incorrect.

**Comment by zuohaocheng** [comment]
@AndrewKirkovski Just wanna check, has this issue been resolved in latest version?

**Comment by Xecutor** [comment]
I don't know if it's related, at least it looks similar, but when I added paper.js to the project, source-map-loader is breaking on line:
`code += "\n//# sourceMappingURL=data:application/json;base64,"`

**Comment by zuohaocheng** [comment]
@Xecutor Thanks for feedback. May I have more information, e.g. version of `source-map-loader` and a sample file?

**Comment by Xecutor** [comment]
@zuohaocheng You can try to build the "project" from this repo: https://github.com/Xecutor/ruleandpencil with webpack. I created it yesterday, so everything should be quite fresh...
