### ISSUE TITLE
Loading preexisting source map: "Unexpected token"

### ISSUE THREAD

**Issue by kraftwer1** [webpack-contrib/source-map-loader#42]
I'm trying to load a preexisting source map using:

    rules: [
        {test: /\.js$/, use: "source-map-loader", enforce: "pre"}
    ]

Unfortunately, I'm getting this warning:

    WARNING in ./modules/MyFile.js.map
    Module parse failed: /Users/me/MyFile.js.map Unexpected token (1:10)
    You may need an appropriate loader to handle this file type.
    | {"version":3,"file":"MyFile.js","sourceRoot":"","sources":["components/MyFile.tsx"],"names":[],"mappings":"AAAA,qCAAqC;;;;;;;;;;;;;AAErC,[...],GA2BnD"}

The source map was originally built by the TypeScript compiler. But in my opinion, this shouldn't matter, since it is a standardized format and `source-map-loader`should probably not have a problem with that.

I'm using the latest stable of Webpack (2.3.3) as well as the latest stable of source-map-loader (0.2.1).

**Comment by michael-ciniawsky** [comment]
@kraftwer1 `source-map-loader` doesn't seem to get trigger at all, because the `test` RegExp is off :) Please try the following

```diff
- { test: /\.js$/, use: "source-map-loader", enforce: "pre" }
+ { test: /\.js\.map$/, use: "source-map-loader", enforce: "pre" }
```

**Comment by kraftwer1** [comment]
Thanks, tried it, but still no success (same warnings). My config looks like that now:

    const modulesPath = path.resolve(path.join(__dirname, "modules"));

    module.exports = {
        ...
        resolve: {
            ...
            extensions: [".webpack.js", ".web.js", ".js", ".js.map"]
        },
        module: {
            rules: [
                    {test: new RegExp(modulesPath+"\/.*\.js\.map$"), use: "source-map-loader", enforce: "pre"}
            ],
            loaders: [
                {test: new RegExp(modulesPath+"\/.*\.js$"), loader: "react-hot-loader"}
                ...
            ]
        }
    }

**Comment by michael-ciniawsky** [comment]
@kraftwer1 Coud you try without 

- `config.resolve`
- `test: /\.js\.map/`
- `react-hot-loader` in `config.module.rules` aswell, and rm `config.loaders`

```diff
- const modulesPath = path.resolve(path.join(__dirname, "modules"));
+ const modulesPath = path.resolve(__dirname, "modules"); // path.resolve also joines :)
```

**Comment by kraftwer1** [comment]
Thanks again. Unfortunately, the same error.
Note that I can't leave `config.resolve` away, otherwise it can't find my Node modules.

Actual config is:

    const modulesPath = path.resolve(__dirname, "modules");

    module.exports = {
        ...
        resolve: {
            modules: [
                path.resolve("folder1/node_modules"),
                path.resolve("folder2/node_modules")
            ],
            extensions: [".webpack.js", ".web.js", ".js", ".js.map"]
        },
        module: {
            rules: [
                {test: /\.js\.map/, use: "source-map-loader", enforce: "pre"},
                {test: /\.js$/, use: "react-hot-loader"}
            ]
        }
    }

**Comment by michael-ciniawsky** [comment]
hmm... by rm `config.resolve` the important part is `extensions` => `.js.map`, also maybe without `react-hot-loader`, at best just with `source-map-loader` for now, to debug

**Comment by michael-ciniawsky** [comment]
btw why `{ enforce: 'pre' }` there is no other loader running in this rule 😛

**Comment by kraftwer1** [comment]
Now I have uncommented as you suggested. Error is: `Module not found: Error: Can't resolve 'react'.`

Config:

    module.exports = {
        ...
        module: {
            rules: [
                {test: /\.js\.map/, use: "source-map-loader"}
            ]
        }
    }

**Comment by michael-ciniawsky** [comment]
That's confusing it's just a `node_module` and should work out-of-the-box with webpack is it installed correctly ?

**Comment by kraftwer1** [comment]
Yes, but there's another `node_modules` folder that is also providing packages.

**Comment by michael-ciniawsky** [comment]
Ohh... 😛 I can't tell you how-to out of the gut sry, but maybe the docs [Resolve](https://webpack.js.org/configuration/resolve/) can give the necessary hint on how-to setup multiple `node_modules` folder and tell the webpack resolver to resolve them correctly

**Comment by TAGC** [comment]
> @kraftwer1 source-map-loader doesn't seem to get trigger at all, because the test RegExp is off :)

If that's the wrong pattern, why is that the pattern used in this project's README?

**Comment by michael-ciniawsky** [comment]
@TAGC 

**index.map.js**
```js
{
   test: /\.js$/ // ok
}
```

**index.js.map**
```js
{
  test: /\.js\.map$/
 // test: /\.map$/
}
```

**Comment by TAGC** [comment]
Oh okay.

**Comment by hiradimir** [comment]
@kraftwer1 
I had same issue, and solve it.

It is not occured by source-map-loader.
This problem was occured this problem by pure webpack config, not include devtool, source-loader etc..
I think almost webpack/typescript user using ts-loader.

----

### Solution

I am using `ignore-loader`
see https://stackoverflow.com/a/39886771/1960600

----

> yarn add -D ignore-loader

```js
module.exports = {
    module: {
        rules: [
            ...
            {
                test: /\.js.map$/,
                loader: 'ignore-loader'
            }
        ]
    },
```

---

Now, I can debug with source-map what typescript generate.
And webpack not showing `WARNING  ~~ Unexpected token`
