### ISSUE TITLE
Add support for disable `emitWarning`

### ISSUE THREAD

**Issue by swernerx** [webpack-contrib/source-map-loader#49]
Currently the loader warns on 3rd party packages which have some invalid source maps. As this is typically not in the hand of the user to fix those (other than send bug reports/PRs) we should offer an option to disable warnings. 

A pretty common error seems to be that source maps are included in the package, but the source maps do not contain the original source content. The references to any files break because the source files are not bundled in the npm packages.

Affected packages in my case are:

- All packages from formatjs (intl-messageformat, ...)
- All packages from Apollo (apollo-client, ...)

**Comment by swernerx** [comment]
This is related to: https://github.com/webpack-contrib/source-map-loader/issues/18

**Comment by swernerx** [comment]
This would be fixed by my PR: https://github.com/webpack-contrib/source-map-loader/pull/50

**Comment by tadamczak** [comment]
Any chances to have it merged any time soon?

**Comment by PachowStudios** [comment]
It'd be really great if this got merged. This loader is basically unusable for me otherwise.

**Comment by cdeutsch** [comment]
Shame this was never fixed. 

Useful plugin, but not going to deal with constant toasts when combined with `webpack-build-notifier`

**Comment by cdeutsch** [comment]
Follow up:

[webpack-filter-warnings-plugin](https://github.com/mattlewis92/webpack-filter-warnings-plugin/tree/v1.2.1) worked for me.

```ts
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');

plugins: [
  // Hide warnings from `source-map-loader`.
  new FilterWarningsPlugin({
    exclude: /node_modules\/source-map-loader\/index/,
  }),
]
```

Be careful when using `webpack-filter-warnings-plugin`, currently the docs in `master` don't match the latest version. 
https://github.com/mattlewis92/webpack-filter-warnings-plugin/issues/4
