### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by QuentinRoy** [webpack-contrib/source-map-loader#51]
If several vendor's source map use the same file-name or the same root directory, only one of them shown in Google Chrome (I haven't tested it with other browsers).
This might be an issue in particular as some directories are very common—e.g. `src`.
Note that the source map is still here (you can find it by stepping into the corresponding function for example), it is just not shown in the sources pane.
I honestly don't know how source-maps work behind the scene, but I am wondering if it would be possible to add a prefix to the source map? Or making it appears in a directory with the name of the imported file?

**Comment by AlexanderOMara** [comment]
This issue has been bugging me for a while.

When it loads existing source maps (from `node_modules` for example) the path is preserved, you can end up with multiple source maps at the same path.

So if you have multiple files with a source map like this:

```json
{
...
  "sources":["src/index.js"],
...
}
```

You end up with a source map listing only one of those files like (thus mapping is lost):

```json
{
...
  "sources" : [
    "webpack:///webpack/bootstrap 935da6b8229a50276409",
    "webpack:///./main.js",
    "webpack:///src/index.js"
  ],
...
}
```

This is very unpleasant, and makes loading sources from outside your code basically unusable.

It would be nice if there was some way to namespace or remap those sources somehow.

**Comment by pixeldrew** [comment]
looks like all node_modules paths are removed. This makes this component basically useless.
