### ISSUE TITLE
increase source-map package version ( Cannot read property 'substr' of undefined err )

### ISSUE THREAD

**Issue by dmitrykurmanov** [webpack-contrib/source-map-loader#54]
Hello, team! Thanks for your work! Can you increase `source-map` package version to the latest (~0.6.1)? This is need beacuse of bug in `source-map` package: https://github.com/mozilla/source-map/issues/247.  I am using preact and the bug is reproducing for me.

and the same https://github.com/webpack/webpack-sources/pull/27

**Comment by Hotell** [comment]
same here

**Comment by evilebottnawi** [comment]
@Hotell done https://github.com/webpack-contrib/source-map-loader/pull/56

**Comment by Hotell** [comment]
release new version plzzzzzz 🍻

**Comment by Hotell** [comment]
strange thing is, that update loader still doesn't work with latest webpack :(

**Comment by evilebottnawi** [comment]
@Hotell please create minimum reproducible test repo, thank you!

**Comment by tomasdev** [comment]
Not sure if this is even possible, but when having multiple dependencies on a project (i.e., babel-cli) it's not always taking the highest version of the sub-dependency.

Given babel-cli@6.26 and source-map-loader@0.2.3 it ends up installing source-map@0.5.7 :(

I have tried explicitly adding `"source-map": "^0.6.1",` to my package.json without success

**Comment by tomasdev** [comment]
Alt solution until this is merged:

1) `npm shrinkwrap` will generate a npm-shrinkwrap.json
2) Find `"webpack-sources": {` and replace it with:
```"webpack-sources": {
      "version": "1.0.1",
      "from": "webpack-sources@>=1.0.1 <2.0.0",
      "resolved": "https://registry.npmjs.org/webpack-sources/-/webpack-sources-1.0.1.tgz",
      "dev": true,
      "dependencies": {
        "source-map": {
          "version": "0.6.1",
          "from": "source-map@>=0.5.3",
          "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz",
          "dev": true
        }
      }
    },```

n-joy
