### ISSUE TITLE
source-map-loader appears not to handle (pass-through) sourcemaps that use http: instead of file:

### ISSUE THREAD

**Issue by aappddeevv** [webpack-contrib/source-map-loader#58]
I have some `http:` source map locations instead of `file:`. It's a bit difficult to tell if this warning is being issued by source-map-loader , but I get alot of warnings around `(Emitted value instead of an instance of Error) Cannot find file https://...`.  Resolution fails for those. If its a Warning its not preventing the build but it would be nice to be able to turn these off while still leaving other types of warnings that are not related to `http:` located source maps.

**Comment by michael-ciniawsky** [comment]
There is a PR to silence warnings in general (#50), the warning you get is correct since the source-map-loader` doesn't fetch source maps via `http` and therefore can't resolve paths starting with `http(s)://` etc
