### ISSUE TITLE
Sourcemap Loader Crashes Webpack 

### ISSUE THREAD

**Issue by egucciar** [webpack-contrib/source-map-loader#65]
Hello!

How can i get this error to stop crashin webpack?

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
     /node_modules/source-map-loader/index.js:53:22
```

this happens quite frequently. I am unsure of the reason why. but, thats how it is.

Instead of crashing, id like it to emit no error, and then try again on any file change.

**Comment by evilebottnawi** [comment]
@egucciar feel free to send a PR

**Comment by fimius23** [comment]
I'm having issues with this too. Intermittently when webpack 4 builds my source maps the file ends with an extra "} which makes it malformed JSON. Seems like this library should consider wrapping the JSON.parse() on the line mentioned above in a try/catch, so a malformed map doesn't stop execution in its tracks.

**Comment by evilebottnawi** [comment]
Fixed in master
