### ISSUE TITLE
Loading Sourcemaps for own Library in Webpack 4

### ISSUE THREAD

**Issue by sqwk** [webpack-contrib/source-map-loader#66]
I have a library `MyLibrary` that is loaded inside `MyApp`. Ever since upgrading to webpack 4, sourcemaps no longer get loaded by the app to debug into the library and only the webpack compiled code is shown. Sourcemaps for each the library and the app itself work fine.

A minimum reproducible repo can be found here: https://github.com/sqwk/webpack-library-test

Also see this Stackoverflow question about the topic: https://stackoverflow.com/questions/50910220/webpack-4-load-library-sourcemap/51253629#

Is this a configuration error or is there a known incompatibility with webpack 4?

**Comment by mfedderly** [comment]
I think that this depends on the devtool setting of the final webpack step. `cheap-eval-source-map` doesn't give me the sourcemaps I'm looking for but `eval-source-map` does. I suspect you need the "original source" devtools.

**Comment by michael-ciniawsky** [comment]
@sqwk Did you find a solution ?

**Comment by sqwk** [comment]
@michael-ciniawsky Afraid not.

**Comment by michael-ciniawsky** [comment]
hmmm... 😞 😛 ok I will try to look at it again when have the time, it's still a bit hard to pinpoint it with the reproduction repo

**Comment by brcarey** [comment]
Big +1 on this. Spent some time trying to debug/diagnose the issue and try out some solutions, and came up with nothing.

**Comment by brcarey** [comment]
Update: seems the problem for me was cheap-module-source-map. As soon as I changed my dev build to use inline-source-map, source-map-loader works fine for my lib packages

**Comment by evilebottnawi** [comment]
When you build library for publishing you should use `devtool: 'source-map'` value if you want provide source maps for other developers (`source-map-loader` automatically loads them). Sorry it's out of our control. In most tools for building library it is described https://webpack.js.org/configuration/devtool/#production. Anyway if you want to send a PR with docs here feel free to do it.
