### ISSUE TITLE
Root-relative sourcemaps have an issue on non-Windows platforms.

### ISSUE THREAD

**Issue by iclanton** [webpack-contrib/source-map-loader#69]
I've found that `source-map-loader` doesn't correctly handle sourcemaps with root-relative `sourceRoot` properties in sourcemaps. I've put together a fix here: https://github.com/webpack-contrib/source-map-loader/pull/68

**Comment by michael-ciniawsky** [comment]
Fixed by #68 and will be released soon (~1 day) after some additional chores like e.g #71 :)

**Comment by michael-ciniawsky** [comment]
Released in [`v0.2.4`](https://github.com/webpack-contrib/source-map-loader/releases/tag/v0.2.4) 🎉
