### ISSUE TITLE
Emitted value instead of an instance of Error.  (warning in webpack build)

### ISSUE THREAD

**Issue by hannadrehman** [webpack-contrib/source-map-loader#73]
i am using lerna and needed this plugin to get sourcemap for lerna packages.  but i am getting this warning after every build. 

```
Emitted value instead of an instance of Error. 
Cannot find SourceMap 'mutationobserver.map': 
Error: Can't resolve './mutationobserver.map' in 
'/<myDir>/node_modules/mutationobserver-shim/dist'
```

this is my loader config 

```
 {
          test: /\.jsx$/,
          use: ['source-map-loader'],
          enforce: 'pre',
        },
        {
          test: /\.js$/,
          use: ['source-map-loader'],
          enforce: 'pre',
        },
```

**Comment by exclusiveMonkey** [comment]
hello, do you resolve this problem?

**Comment by hannadrehman** [comment]
@exclusiveMonkey not yet. still waiting for the maintainers to respond

**Comment by PeacePan** [comment]
It seems that the polyfill repository forgot to generate the source map.
[issue](https://github.com/megawac/MutationObserver.js/issues/29)

**Comment by PeacePan** [comment]
if this issue still existed, you can use exclude option.
> 
{

	test: /\.js$/,
	use: ['source-map-loader'],
	enforce: "pre",
	exclude: [
		/node_modules\/mutationobserver-shim/g,
	],
}

**Comment by subramn** [comment]
Same issue with  ngx-cookie-service as well, is there a work around

**Comment by evilebottnawi** [comment]
Fixed in the master, ETA is the tomorrow
