### ISSUE TITLE
file name collision for source map source location in microservices architecture

### ISSUE THREAD

**Issue by harish-kumar13** [webpack-contrib/source-map-loader#80]
So I have a angular System app that makes use of component from several micro-services libraries, and in my domain, there are few common concepts that have different purpose in different services, and the individual JS names can be the same on different services.
So when source-map-loader extracts the JS src locations from each of these libraries, the file names and their relative paths can collide, and webpack would show only the last file that it copied over with the same name.
Any work around to this or is anything planned around this, or any recommendation.

For example.
Shipping --> Has a JS named order.js at location ./app/order.js
Fullfilment --> Has a JS named order.js at location ./app/order.js

source maps would point to these location in their respective projects. Source maps on both services would have below entry in their JS.  
e.g. /***/ "./app/order.js":

When source-map-loader extracts this info chrome debugger would map both these files to below location
webpack:///webpack:///app/order.js

**Comment by bennidhamma** [comment]
I'm experiencing the same issue

**Comment by cap-Bernardito** [comment]
A same problem #51. Will be resolved there.
