### ISSUE TITLE
source-map-loader don't exclude node_modules

### ISSUE THREAD

**Issue by Iplaylf2** [webpack-contrib/source-map-loader#81]
I just make a "hello world" demo.The dist file only take 60k when I use react+ts.But,it will take 15M when I reference antd library。  
About ts-loader
```
      {
        test: /\.(ts|tsx)?$/,
        loader: "awesome-typescript-loader"
      },
```

About source-map-loader
```
      {
        test: /\.(tsx|ts|jsx|js)$/,
        exclude: path.resolve(__dirname, "node_modules"),
        use: ["source-map-loader"],
        enforce: "pre"
      }
```

source-map-loader not working.The result as same as only set   ```devtool: "inline-source-map"```

Thank you for reading my shit English.I try resolving it by myself.But I even found not one demo about this loader.Sorry~

**Comment by evilebottnawi** [comment]
It is expected, and written in README:
```
`source-map-loader` will extract from any JavaScript file, including those in the `node_modules` directory.
```
