### ISSUE TITLE
Source Map Revision 3 Index Map Not Supported

### ISSUE THREAD

**Issue by NoxHarmonium** [webpack-contrib/source-map-loader#89]
Hi,

I have a project that is written in ClojureScript. When it outputs source maps it seems to use a format that is in the [Source Map Revision 3 spec](https://sourcemaps.info/spec.html) but is not supported by `source-map-loader`.

It seems like the error is caused because the source map uses the alternate "Index map" form, which does not have the `sources` key at the root, it has a `sections` key which has an array of maps.

See: https://sourcemaps.info/spec.html#h.535es3xeprgt

The exact error I get when trying to load the source map in through webpack is:

> 
> ...node_modules/source-map-loader/index.js:74
>                         map.sources = map.sources.map(function(s) { return sourcePrefix + s; });
>                                                   ^
> 
> TypeError: Cannot read property 'map' of undefined
>     at processMap (.../node_modules/source-map-loader/index.js:74:30)
>     at .../node_modules/source-map-loader/index.js:59:6
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

It mustn't be a format that is commonly used or this issue would have come up before (unless I'm misunderstanding something)

I've attached a sample of the output file and source map that is causing the issue.

[example.zip](https://github.com/webpack-contrib/source-map-loader/files/3562122/example.zip)

The ClojureScript project that outputs the library/source map is: https://github.com/agiledigital/mule-preview/tree/master/client
The webpack project that is consuming the source map is: https://github.com/agiledigital/mule-preview/tree/master/browser-plugin

I haven't had a look yet at how hard this would be to fix, it might be as simple as iterating over each section, or we might have to pre process the source map with something like https://github.com/mozilla/source-map

Hopefully I'll have some time to do some digging into the spec soon.

Thanks!

**Comment by NoxHarmonium** [comment]
Related: https://github.com/mozilla/source-map/issues/16

**Comment by NoxHarmonium** [comment]
I've created a fork that uses an external library to flatten indexed maps.
https://github.com/NoxHarmonium/source-map-loader/commit/7b91d7cdd4ab12d5dbb403199754a58469aeaf90
It seems to be working, I'm just giving it a good test now.

**Comment by NoxHarmonium** [comment]
Seems to be working well for me, I'll open a PR and see what people think of the fix

**Comment by aisamu** [comment]
Running into the exact same issue! (Also a clojurescript project)

**Comment by aisamu** [comment]
Confirmed that it works with the patch!

**Comment by cap-Bernardito** [comment]
@NoxHarmonium, thanks for the help in solving this problem.

We decided not to use the `flatten-source-map` package, because it is little used and contains an old version of `source-map` package.

If you find any problems, please report.

**Comment by NoxHarmonium** [comment]
> We decided not to use the flatten-source-map package, because it is little used and contains an old version of source-map package.

Good point! I've tested it in my project and its working great. Thanks for getting the fix in!
